dataset:
  date_file: "data/waveform_data"
params:
  patch_size: 128
  stride: 1
  top_k: 3
  in_channels: 1

model:
  model_path: "output/trained_model.pt"
  memory_bank_path: "output/memory_bank.npy"
  
output:
  score_dir: "data/anomaly_scores"
